[package]
name = "hypersweeper"
authors = ["Timbits"]
version = "0.0.1"
edition = "2021"

[dependencies]
bitpacking = "0.9.2"
itertools = "0.13.0"
packed_struct = "0.10.1"
rand = "0.8.5"
rayon = "1.10.0"
